<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.15</version>
        <relativePath/>
    </parent>

    <groupId>com.isom</groupId>
    <artifactId>data-server-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>data-server-parent</name>

    <modules>
        <module>data-server-runtime</module>
        <module>data-server-admin-app</module>
        <module>data-server-gateway-app</module>
    </modules>

    <properties>
        <java.version>1.8</java.version>
        <mybatis-plus.version>3.5.3.1</mybatis-plus.version>
        <sa-token.version>1.37.0</sa-token.version>
        <hutool.version>5.8.25</hutool.version>
        <knife4j.version>4.4.0</knife4j.version>
        <bcprov.version>1.70</bcprov.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.isom</groupId>
                <artifactId>data-server-runtime</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
